### ISSUE TITLE
cordova-plugin-health not working with productive app on Google Play

### ISSUE THREAD

**Issue by mardugas** [dariosalvi78/cordova-plugin-health#112] opened 2018-06-30 20:34 UTC
I'm developing a health app and I want to use cordova-plugin-health to read step counts.
It is working correctly when I install the App from my local PC via USB cable on my Android smartphone.
I generated an OAuthClient-ID using https://code.google.com/apis/console/?pli=1 for the app.

I uploaded my app using Play Console to Google Play. I generated an additional OAuthClient-ID with the SHA1-signature from Google Play. When I download the App from Google Play, cordova-plugin-health does not return any value, and there is no error message. I tested different OAuthClient-IDs, but id did not work (when I used a wrong OAuthClient-ID with my test app, there was an error message).
Thanks for Your help

**Comment by dariosalvi78** [comment] 2018-07-01 13:19
looks like an oath issue. Please be aware that the keys used for debugging are not the same used for releases. 
In doubt, as stated in README, you can type `keytool -list -printcert -jarfile yourapp.apk` to know what keys you are apk is using.

**Comment by mardugas** [comment] 2018-07-01 19:48
I checked keytool / SHA1 signature. I tried it with my own SHA1 production signature as well as Googles SHA1 signature, but no success.
Interestingly, there is no error message with the App from Google Play
(in contrast, when I developed my test app and did not yet have the correct OAuth-Client-ID, there was an error message)

**Comment by conormag** [comment] 2018-07-05 18:50
I have the same issue as OP. When I am in development everything works perfectly and when I release to production the plugin returns no data. Also, in production I do not get the auth modals for location sensing or fitness. I have treble-checked everything related to certificates/signing and it is correct - it only shows the modal to select a google account.

**Comment by dariosalviwork** [comment] 2018-07-15 08:52
I can't check now as I'm away. I'd just suggest to check again [against the official guidelines](https://developers.google.com/fit/android/get-api-key).

**Comment by dariosalviwork** [comment] 2018-07-31 15:52
I've just made another release of my app with the latest version of this plugin and everything works as expected. I don't think the problem is related to the plugin, it should have to do with your oauth settings.

**Comment by dariosalviwork** [comment] 2018-09-28 11:33
shall I close this issue?

**Closed** 2018-09-28 12:43 UTC
Labels: help wanted
