### ISSUE TITLE
Project doesn't compile after installing health native plugin

### ISSUE THREAD

**Issue by danishmanzoormalik** [dariosalvi78/cordova-plugin-health#151] opened 2019-05-04 13:59 UTC
Hi,
Whenever I install this plugin app stops building and I face this error. I have looked on ionic community another user was facing same issue. Please look into this issue.

regards.

Ionic:

   ionic (Ionic CLI)  : 4.12.0 (C:\Users\Username\AppData\Roaming\npm\node_modules\ionic)
   Ionic Framework    : ionic-angular 3.9.5
   @ionic/app-scripts : 3.2.2

Cordova:

   cordova (Cordova CLI) : 7.0.1
   Cordova Platforms     : android 6.2.3
   Cordova Plugins       : cordova-plugin-ionic-keyboard 2.0.5, cordova-plugin-ionic-webview 4.0.0, (and 4 other plugins)

System:

 (C:\Program Files (x86)\Android\android-sdk)
   NodeJS            : v6.9.2 (C:\Program Files\nodejs\node.exe)
   npm               : 5.3.0
   OS                : Windows 10

Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
Error: cmd: Command failed with exit code 1 Error output:
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
D:\ionic 2\myapp\platforms\android\src\org\apache\cordova\health\HealthPlugin.java:574: error: cannot find symbol
            builder.addScope(new Scope(Scopes.FITNESS_BLOOD_GLUCOSE_READ));
                                             ^
  symbol:   variable FITNESS_BLOOD_GLUCOSE_READ
  location: class Scopes
D:\ionic 2\myapp\platforms\android\src\org\apache\cordova\health\HealthPlugin.java:576: error: cannot find symbol
            builder.addScope(new Scope(Scopes.FITNESS_BLOOD_GLUCOSE_READ_WRITE));
                                             ^
  symbol:   variable FITNESS_BLOOD_GLUCOSE_READ_WRITE
  location: class Scopes
D:\ionic 2\myapp\platforms\android\src\org\apache\cordova\health\HealthPlugin.java:579: error: cannot find symbol
            builder.addScope(new Scope(Scopes.FITNESS_BLOOD_PRESSURE_READ));
                                             ^
  symbol:   variable FITNESS_BLOOD_PRESSURE_READ
  location: class Scopes
D:\ionic 2\myapp\platforms\android\src\org\apache\cordova\health\HealthPlugin.java:581: error: cannot find symbol
            builder.addScope(new Scope(Scopes.FITNESS_BLOOD_PRESSURE_READ_WRITE));
                                             ^
  symbol:   variable FITNESS_BLOOD_PRESSURE_READ_WRITE
  location: class Scopes
Note: D:\ionic 2\myapp\platforms\android\src\org\apache\cordova\splashscreen\SplashScreen.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
4 errors

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

**Comment by dariosalvi78** [comment] 2019-05-04 16:42
duplicate of #128

**Closed by dariosalvi78** 2019-05-04 16:42 UTC
