### ISSUE TITLE
[Google Fit] Import manualy added Sleep

### ISSUE THREAD

**Issue by andreiropotica** [dariosalvi78/cordova-plugin-health#190] opened 2020-11-24 09:09 UTC
Hello, 

The plugin does not import manually added sleep on my phone, only the automatic ones from Mi Fit app, recorded with my Mi Band 4.

Can you help me with this issue?

Aditional info:
- plugin version: 2.0.0 (same issue with 1.1.4)
- android version: 10
- gfit app: 2.45.13-130

Thank you!
Andrei

**Comment by dariosalvi78** [comment] 2020-11-24 10:08
if it's on Google Fit it should be retrieved by the plugin in principle.
The manual add of sleep was added on Google Fit only recently, maybe there's a bug?

**Comment by andreiropotica** [comment] 2020-11-24 11:06
I added manually a sleep a few months ago (August)... that one is still imported now, but any manual sleeps I add are not retrieved.

I colleagues of mine added a manual sleep yesterday, and it got imported on an older android version...

Could you please check, if on your app, a manual sleep is retrieved?

Maybe it's related to these changes? https://developers.google.com/fit/improvements#rest

Thank you!
Andrei

**Comment by dariosalvi78** [comment] 2020-11-24 13:22
mmm, i t actually may be because of [this change](https://developers.google.com/fit/improvements#separate_scopes_and_new_data_type_for_sleep) actually. Would you be able to help with this?

**Comment by dariosalvi78** [comment] 2020-11-24 13:29
I have just pushed a change to solve the issue related to the read/write permissions. Can you check if that solves your problem? Try with the latest version on git instead of the official release.

If that doesn't solve it, it may be related to the new sleep data type, which I like a lot because it's more similar to what actually HealthKit does, but this would require more work and possibly also some API breaking change.

**Comment by andreiropotica** [comment] 2020-11-25 07:53
Unfortunately, I cannot help you with the fix, I am not familiar with Java.

I just tested the latest version, but it did not fix the sleep issue.

**Comment by dariosalvi78** [comment] 2020-11-25 09:29
then the problem is probably related to the fact that sleep has been now separated from activity. It's strange that the Xiaomi app is still writing it as activity, but maybe that's because it uses an older version of the SDK and Google kept compatibility.

So basically this is now a mess: some apps will write sleep as activity and some as proper sleep. My plan is to switch to the new "sleep only system", but I'm busy at the moment. I can't say exactly when this will be available (a month maybe?), unless someone here wants to help!

**Comment by dariosalvi78** [comment] 2020-11-25 09:30
duplicate of #191

**Closed by dariosalvi78** 2020-11-25 09:30 UTC
