### ISSUE TITLE
Didn't get the heart rate, blood pressure rate and sleep rate values

### ISSUE THREAD

**Issue by GobinathKPerumal** [dariosalvi78/cordova-plugin-health#275] opened 2023-01-23 07:51 UTC
Hi @dariosalvi78, we are currently using cordova-plugin-health for google fit integration, In Android last few months it didn't retrieve the values for heart rate, blood pressure rate, and sleep rate.

can you explain why we are facing this issue in our plugin?

And please confirm when this issue is fixed and when we expect the updated cordova-plugin-health plugin.

or suggest me if any new plugins for getting these values in Android cordova.

**Comment by dariosalvi78** [comment] 2023-01-23 08:18
I cannot answer this question without further details. There have been some changes recently, but they only concern sleep. My last tests were all positive, but I haven't tested all the data types.

Please perform some tests to confirm that there is indeed a bug and provide details. If you find the cause you are very welcome to fix it and send a pull request.

**Comment by GobinathKPerumal** [comment] 2023-01-23 09:28
You mentioned you get the sleep data after recently making some changes, but we didn't get sleep data also.

can you share your mail id, we will reach out through the mail.

Note: We are the new user of cordova-pugin-health

**Comment by dariosalvi78** [comment] 2023-01-23 09:34
email is like my user on Github at gmail. If there is anything that can be of interest for others, I would like to keep it here.

**Comment by GobinathKPerumal** [comment] 2023-01-31 03:48
@dariosalvi78 , you mentioned sleep data is working properly, okay fine, if you get heart rate value from our plugin (cordova-plugin-health) ?

**Comment by GobinathKPerumal** [comment] 2023-01-31 03:50
we are facing Datatype not supported error for both sleep and heart rate, here I attached the error logs also please find it
![WhatsApp Image 2023-01-30 at 7 24 24 PM](https://user-images.githubusercontent.com/109264156/215658475-0aef0b4a-9c06-4cee-af81-5b456c8dc109.jpeg)

**Comment by dariosalvi78** [comment] 2023-01-31 08:52
Can you please specify if this is on Android or iOS and what the query looks like?

**Comment by GobinathKPerumal** [comment] 2023-01-31 08:53
This issue happens in Android and this looks like datatype mismatch issue

**Comment by GobinathKPerumal** [comment] 2023-02-08 11:33
@dariosalvi78 , any update?

**Comment by dariosalvi78** [comment] 2023-02-17 21:05
I have run my test app, Android, latest version of the plugin and latest version of the cordova Android platform (11.0.0).

Querying sleep:
```
navigator.health.requestAuthorization(['sleep'], ok, err)

navigator.health.query({
  startDate: new Date(new Date().getTime() - 3 * 24 * 60 * 60 * 1000),
  endDate: new Date(), // now
  dataType: 'sleep',
  limit: 1000
}, ok, err)
```
got a result.

Querying heart rate:
```
navigator.health.requestAuthorization(['heart_rate'], ok, err)

navigator.health.query({
  startDate: new Date(new Date().getTime() - 1 * 24 * 60 * 60 * 1000),
  endDate: new Date(), // now
  dataType: 'heart_rate',
  limit: 1000
}, ok, err)
```
got a result.

Querying heart rate:
```
navigator.health.requestAuthorization(['blood_pressure'], ok, err)

navigator.health.query({
  startDate: new Date(new Date().getTime() - 1 * 24 * 60 * 60 * 1000),
  endDate: new Date(), // now
  dataType: 'blood_pressure',
  limit: 1000
}, ok, err)
```
got an empty result because I don't have any BP values on my phone.

Closing for not being able to reproduce the bug.

**Closed by dariosalvi78** 2023-02-17 21:05 UTC

**Comment by GobinathKPerumal** [comment] 2023-02-19 06:33
Thanks @dariosalvi78
