### ISSUE TITLE
Issue in IOS 12

### ISSUE THREAD

**Issue by hasib2cool** [dariosalvi78/cordova-plugin-health#143] opened 2019-03-12 06:02 UTC
Dear Team ,
It is not working after i updated my phone to ios 12. It was working fine in ios11.
Please test it in IOS 12 latest update 12.1.4.
Regards,

**Comment by dariosalvi78** [comment] 2019-03-19 15:45
looks like a duplicate of #135. Have you found any error message? Can you describe what happens?

**Comment by hasib2cool** [comment] 2019-03-25 11:42
No i am not finding any error message.
Even it is not asking for permissions.

**Comment by dariosalviwork** [comment] 2019-04-02 14:33
Tested here on ios 12.2 and it works.

It's very likely that you have forgotten to set the HEALTH_READ_PERMISSION and HEALTH_WRITE_PERMISSION, or that those were deleted for some reason.

Check if you get something similar in your xcode console:

> NSHealthUpdateUsageDescription must be set in the app's Info.plist in order to request write authorization for the following types....

**Closed by dariosalviwork** 2019-04-02 14:33 UTC
