### ISSUE TITLE
Cannot set privacy policy URL

### ISSUE THREAD

**Issue by MrJustreborn** [dariosalvi78/cordova-plugin-health#304] opened 2024-01-08 10:12 UTC
When calling 
`cordova.plugins.health.setPrivacyPolicyURL("https://example.com", () => {  
        console.info("YES! - privacy set")  
      }, (e: any) => {  
        console.info("NO! - privacy set:", e)  
      })`

I get the error: 'Class not found'

I'm using ionic with capacitor 5 and cordova-plugin-health: "^3.0.1"

**Comment by dariosalvi78** [comment] 2024-01-08 10:53
where does the error come from? is it the javascript code or is it coming from the Android code?

Are you using @awesome-cordova-plugins ?

**Comment by MrJustreborn** [comment] 2024-01-08 15:02
Yes i also have @awesome-cordova-plugins/health installed.

The error is shown in my javascript console, I don't know where it originates, but it looks like android

**Comment by MrJustreborn** [comment] 2024-01-08 15:03
The other methods, like authorize do work

**Comment by dariosalvi78** [comment] 2024-01-08 15:12
I am afraid that awesome cordova plugins is not updated with the latest version of this plugin. I strongly suggest to avoid it, as it doesn't really give any advantage over using the regular plugin. May be that the reason?
Maybe try with an empty Ionic project to confirm that that is the issue?

Possibly a duplicate of of https://github.com/dariosalvi78/cordova-plugin-health/issues/302

**Comment by dariosalvi78** [comment] 2024-01-09 14:44
If you have fixed the issue, please either write a comment, or close this issue. Thanks

**Comment by MrJustreborn** [comment] 2024-01-15 07:20
Sorry for my late reply.
The issue remains, I created a blank project to reproduce the error:
https://github.com/MrJustreborn/ionicHealthConnectTest

I get the error:
`Class not found`
in my console log.

**Comment by dariosalvi78** [comment] 2024-01-19 17:30
@MrJustreborn does using the default privacypolicy.html inside www work?

**Comment by MrJustreborn** [comment] 2024-01-20 09:40
This file does work.

**Comment by dariosalvi78** [comment] 2024-01-20 16:43
ok, then as a temporary fix, just fill in that file with your privacy policy. I will check the `Class not found problem` meanwhile.

**Closed** 2024-01-22 15:19 UTC
