### ISSUE TITLE
Android - Query Errror- Invalid Date 

### ISSUE THREAD

**Issue by iBoonz** [dariosalvi78/cordova-plugin-health#162] opened 2019-09-22 20:18 UTC
Hi, 

With some of my users I get following error: 
query err"Invalid end time: 1568721803171"
Same with following TimeStamp 1569159652101 
This is thrown in the Query method for an Android User.
When checking these timestamps via https://www.epochconverter.com/, these  are correct.
Any Idea why this error is thrown on some of the  Android devices?

```

` QueryData(): void {
    this.statusChange.next('Start Sync');
    this.health.isAvailable()
      .then((available: boolean) => {
        this.statusChange.next('Available ' + available);
        this.health.requestAuthorization(this.datatTypeReadList).then(authorized => {
          this.statusChange.next('Authorized ' + authorized);
          if (!this.platform.is('ios') && !available) {
            this.health.promptInstallFit();
            return;
          }
          let result: LocalHealthData[] = [];
          let start: Date = new Date();
          this.statusChange.next('Getting Data');
          start.setDate(start.getDate() - 5);
          start.setHours(0, 0, 0);
          let end: Date = new Date();
          end.setHours(23, 59, 59);
          let currentNumberOfQueries: number = 0;
          this.dataTypesToFetch.forEach(dt => {
            let queryOptions: HealthQueryOptions = {
              startDate: start, endDate: end, dataType: dt, limit: 100000
            };
            this.statusChange.next('Performing Query');
            this.health.query(queryOptions).then(foundHealthDataCollection => {
              currentNumberOfQueries += 1;
              foundHealthDataCollection.forEach(healthData => {
                let sourceBundleId: string = healthData.sourceBundleId;
                if (!sourceBundleId || sourceBundleId.length === 0) {
                  sourceBundleId = this.platform.is('ios') ? 'com.apple.health' : 'com.android.health';
                }

                let localHealthData: LocalHealthData = {
                  startDate: healthData.startDate,
                  endDate: healthData.endDate,
                  type: dt,
                  unit: healthData.unit,
                  sourceBundleId: sourceBundleId,
                  sourceName: healthData.sourceName,
                  value: healthData.value,
                  device: this.platform.is('ios') ? 'ios' : 'android'
                };

                result.push(localHealthData);
              });

              if (currentNumberOfQueries === 3) {
                if (result.length !== 0) {
                  this.statusChange.next('Saving');
                  this.activitiesHttpService.Post(result).subscribe(data => { });
                } else {
                  this.statusChange.next('no items found');
                }
                this.activitiesHttpService.PostActivityMetdata(status).subscribe(data => { });
              }
            }, (e) => {
              this.statusChange.next('query errror: ' + JSON.stringify(e));
              this.activitiesHttpService.PostActivityMetdata('query err' + JSON.stringify(e)).subscribe(data => { });
            });
          });
        }).catch(e => {
          this.statusChange.next('auth errror: ' + JSON.stringify(e));
          this.activitiesHttpService.PostActivityMetdata('requestAuthorization err' + JSON.stringify(e)).subscribe(data => { });
        });
      })
      .catch(e => {
        this.statusChange.next('unavailable: ' + JSON.stringify(e));
        this.activitiesHttpService.PostActivityMetdata(status).subscribe(data => { });
      });
  }
}`
```

**Comment by dariosalvi78** [comment] 2019-09-23 07:49
it never happened to me.
Does it happen only on some android devices or on all of them?

**Comment by iBoonz** [comment] 2019-09-23 08:54
We recently rolled out to 700+ users in Belgium.
This is now happening with 4 android devices, I am asking for more information what they registered 

We push the error now in the face of the user (no UX friendly ;))

![image](https://user-images.githubusercontent.com/2930374/65412877-6b15ef80-ddf0-11e9-9995-b573164ac5f8.png)

Something I did not mention is that we query for : activity, hearthrate and distance

**Comment by dariosalvi78** [comment] 2019-09-23 09:10
I am really glad this plugin is being used at such scale.

I have no idea why these users are finding this error. Four out of hundreds is really a niche.
My only suspicion is that they have some old version of Android or the Play Services.

You could try detecting the version of both and suggesting them to update their phone?

If the problem is that the timestamps are not interpreted correctly, that is, as millis, but are interpreted as seconds, then an ugly hack would be catching this exception and re-issuing the query with the same timestamp, but divided by 1000.

Hope it helps.

**Comment by iBoonz** [comment] 2019-09-23 09:41
Ha, thanks for the plugin and continuous improvement for this codebase :)
Though, if I test these values in EPOCH converters, i get a correct date: 1568721803171 == Tuesday, September 17, 2019 12:03:23.171 PM

What I currently know is that the user was in the U.K. last week and now synced in Belgium, but I cannot wrap my head around why this would be an issue for the parsing.

**Comment by dariosalvi78** [comment] 2019-09-23 10:04
To clarify what happens, your JS code sends a JS Date which is then converted to millis since 1970, which is then passed to the Fit API as millis. So there should be no problem there, unless there is a bug in the specific version of the Fit API these users are using. It's quite unlikely that the API had such an evident bug and that the user hasn't updated the phone for very long, so I  would exclude this as the cause if your trouble.

The fact that the user switched time zone may suggest something.

1568721803171 means something different depending on the timezone. In Central European Sumer Time, this is equivalent to Sep 17 2019 14:03:23 for example.

When was this query issued? Maybe it was in the future at the time it was issued ? (could happen because of time zone change) Or is this happening now?

**Comment by dariosalvi78** [comment] 2020-01-07 11:59
hi, are you still experiencing this issue?

**Comment by dariosalvi78** [comment] 2020-10-15 11:51
I am going to close this issue, it anyways seems to be related to Google Fit and not to the plugin. 
If you experience this again, it may be worth checking again.

**Closed by dariosalvi78** 2020-10-15 11:51 UTC
