### ISSUE TITLE
Wrong unit value in workout from HealthKit

### ISSUE THREAD

**Issue by marioshtika** [dariosalvi78/cordova-plugin-health#84] opened 2017-10-25 10:31 UTC
Hello,
I am using Health App to retrieve activities. I am using the query method as mentioned in your documentation.
```
navigator.health.query({
  startDate: new Date(new Date().getTime() - 30 * 24 * 60 * 60 * 1000), // last 30 days
  endDate: new Date(), // now
  dataType: 'workouts'
}, successCallback, errorCallback)
```
The data returned have the  "unit":"**activity-Type**" insead of "unit":"**m**"
```
[
    {
        "startDate":"2017-10-06T10:55:00.000Z",
        "endDate":"2017-10-06T10:55:00.000Z",
        "value":"walking",
        "unit":"activity-Type"
        "calories": 59,
        "distance": 900,
        "sourceName": "Health",
        "sourceBundleId":"com.apple.Health",
    }
]
```
Am I doing something wrong?

**Comment by dariosalvi78** [comment] 2017-10-25 10:40
this was already replied, and closed in #82

I'll repeat: calories and distance are only provided by HealthKit at the moment (see issue #41) and  duration is not given, but you can retrieve it by doing endDate - startDate.
I'll close this issue. If you think there's a better answer to it, please reopen it (don't create another one) and write why you are opening it.

**Closed by dariosalvi78** 2017-10-25 10:40 UTC

**Comment by marioshtika** [comment] 2017-10-25 10:47
It is not the same issue I am asking about the value of **unit**.

I am asking, how can I understand if my activity is in **km** or in **miles**

**Comment by marioshtika** [comment] 2017-10-25 10:50
I am sorry if my question are structured in the same way as my previous question. This is a a total different question, while retrieving **workouts** from **HealthKit**

**Comment by dariosalviwork** [comment] 2017-10-25 10:50
Yes, I haven't read it with enough attention.
No, it's not a bug, the activity type is activity, not distance. See README.

**Comment by marioshtika** [comment] 2017-10-25 10:54
Oh, sorry. You are right. 
Is there a way to understand if the distance returned is in **km** or in **miles**?

Thank you in advance and I am sorry for the inconvenience.

**Comment by dariosalviwork** [comment] 2017-10-25 11:23
from the README:

> Activities in HealthKit may include two extra fields: calories (kcal) and distance (m)

**Comment by marioshtika** [comment] 2017-10-25 11:58
I am so sorry. I did read that, I knew it and somewhere in the way I got lost. Thank you again.
