### ISSUE TITLE
Error with Phonegap Build CLI-7.0.1 Missing Info.plist key, Previously Worked

### ISSUE THREAD

**Issue by nicclark** [dariosalvi78/cordova-plugin-health#88] opened 2017-12-12 21:24 UTC
I recently upgraded to CLI-7.0.1 and am now experiencing the following errors.  One for updating.  One for sharing.  As in your instructions I'm using the <config-file> parameters within config.xml.  This worked fine before the upgrade.  Has anyone else experienced this and/or know a solution?  Below the errors are my config-file parameters... 

**ERROR ITMS-90683 - "Missing Info.plist key.**  This app attempts to access privacy-sensitive data without a usage description.  The app's Info.plist must contain and NSHealthShareUsageDescription key with a string value explaining to the user how the app uses this data.

**ERROR ITMS-90683 - "Missing Info.plist key.**  This app attempts to access privacy-sensitive data without a usage description.  The app's Info.plist must contain and NSHealthUpdateUsageDescription key with a string value explaining to the user how the app uses this data.

<config-file platform="ios" target="*-Info.plist" parent="NSHealthShareUsageDescription" mode="replace">
        <string>App would like to access some of your health data.</string>
</config-file>

<config-file platform="ios" target="*-Info.plist" parent="NSHealthUpdateUsageDescription" mode="replace">
        <string>App would like to update some of your health data.</string>
</config-file>

**Comment by dariosalviwork** [comment] 2017-12-13 10:08
I think this is a duplicate of #86.
Please check if the solution works for you.
The README also says:

> If, for some reason, the Info.plist loses the HEALTH_READ_PERMISSION and HEALTH_WRITE_PERMISSION, you probably need to add the following to your project's package.json:
>
>{
>  "cordova": {
>    "plugins": {
>     "cordova-plugin-health": {
>        "HEALTH_READ_PERMISSION": "App needs read access",
>        "HEALTH_WRITE_PERMISSION": "App needs write access"
>      }, },  }  }

If this works, please close this issue.

**Comment by nicclark** [comment] 2017-12-13 16:35
@dariosalviwork Thanks for the quick reply.  I'm not using Ionic.  I'm using Phonegap Build and it does not create a package.json.  Unless I am mistaken...

**Comment by dariosalviwork** [comment] 2017-12-13 16:39
I can't help I'm afraid,
I usually build the apps from Xcode directly and fix stuff in Xcode if needed.
Try creating the package.json yourself, maybe it helps...

**Comment by nicclark** [comment] 2017-12-13 16:43
@dariosalvi78 Thanks

**Comment by nicclark** [comment] 2017-12-13 20:35
Found a solution.  For Phonegap Build cli-7.0.1 you must include this in your config file to install the plugin...

<plugin name="cordova-plugin-health" spec="0.10.1">
     <variable name="HEALTH_READ_PERMISSION" value="YOUR TEXT HERE" />
     <variable name="HEALTH_WRITE_PERMISSION" value="YOUR TEXT HERE" />
</plugin> 

... and then change <config-file> to <edit-config> like this

<platform name="ios">
     <edit-config target="NSHealthShareUsageDescription" file="*-Info.plist" mode="merge">
          <string>YOUR TEXT HERE</string>
     </edit-config>
     <edit-config target="NSHealthUpdateUsageDescription" file="*-Info.plist" mode="merge">
          <string>YOUR TEXT HERE</string>
     </edit-config>
</platform>

**Closed** 2017-12-13 20:42 UTC
