### ISSUE TITLE
Activity doesn't appear in Google Fit, even though store() returns success=true

### ISSUE THREAD

**Issue by nielsjakob** [dariosalvi78/cordova-plugin-health#167] opened 2019-10-16 18:41 UTC
I have my App properly authorized and am running the following code to try and store an activity:

```
navigator.health.isAuthorized(['activity'], function(authorized) {
    console.log('isAuthorized', authorized);
    if(authorized) {
        navigator.health.store({
            startDate:  new Date(new Date().getTime() - 3 * 60 * 1000),
            endDate: new Date(),
            dataType : 'activity',
            value: 'walking',
            sourceName: 'MyAppName'
        }, function(success) {
            console.log('store success', success);
        })
    }
})
```

As expected, I get the console outputs `isAuthorized, true` and `store success, true`. However, **the activity does not appear in the Google Fit app**..

A few notes that might be relevant:
- My apps permissions in the Google Fit app include "Read/Write Fitness Activity Data"
- Storing non-activity data works fine
- Other apps' activities appear in Google Fit.

I am using plugin version 1.1.3 and a Samsung Galaxy S8 with Android 9.

**Comment by dariosalvi78** [comment] 2019-10-16 19:31
what happens if you query for the activity in the same time range?

**Comment by nielsjakob** [comment] 2019-10-17 07:25
Good idea, if I do that, it does return the activity!

Any idea why Google Fit might not want to show it in my "Journal"?

I noticed that other Apps have a name for the activity, like "Evening workout". I have not seen this in the documentation - maybe Google Fit needs that to display the activity?

**Comment by dariosalvi78** [comment] 2019-10-17 10:52
I have no idea why GF doesn't show it. Re. the names, I believe GF decides those names by itself.

**Comment by dariosalvi78** [comment] 2019-10-17 10:52
It looks like the problem is GF not the plugin, I'll close the issue now...

**Closed by dariosalvi78** 2019-10-17 10:52 UTC

**Comment by gylippus** [comment] 2020-02-07 15:49
@dariosalvi78  did you ever come to a resolution for what problem was occurring with GF?

**Comment by dariosalvi78** [comment] 2020-02-07 16:17
which problem? looks like we have 2 problems here:

1. GF not returning an activity if your time window does not include it entirely
2. an activity added with the plugin does not show up in Google Fit

as for n.1 I guess there is no other solution than making sure the window of time of the query contains the activity, as for n.2 I don't know really, it may be that GF only shows some specific activities ?
