### ISSUE TITLE
installation issues ANDROID

### ISSUE THREAD

**Issue by LucianoSchettino** [dariosalvi78/cordova-plugin-health#303] opened 2023-12-19 09:55 UTC
I'm in an Ionic project, I encountered this problem both with Capacitor 5 and 6 and with cordova. 
I followed the instructions in the README but every time I invoke the Health methods from '@awesome-cordova-plugins/health/ngx' the capacitor or cordova console on Android returns:  'Line 1 - Msg: Native: tried calling Health .promptInstallFit, but the Health plugin is not installed.' If I try to run: 'ionic cordova plugin add cordova-plugin-health'  (on the Cordova project) it says plugin already installed. 
Maybe I'm doing something wrong, thanks in advance for your help

**Comment by Schetkiglobe** [comment] 2023-12-19 12:49
@dariosalvi78 
I have also encountered the same issue. I tried to install the plugin both with Capacitor and Cordova. I followed the configuration process, but I was not able to get it to work.

**Comment by dariosalvi78** [comment] 2023-12-19 21:05
duplicate of #302

**Closed by dariosalvi78** 2023-12-19 21:05 UTC

**Comment by dariosalvi78** [comment] 2023-12-19 21:07
salve, the new version of the plugin (3 and up) is a complete reimplementation on the Android side that uses Health Connect instead of Google Fit. The issue you are reporting is that @awesome-cordova-plugins is not updated.

Solutions: use the latest v2, but stick to Google Fit, or do not use @awesome-cordova-plugins (<- I would recommend). It all depends on what API you want to use in the end.

Let me know if you manage to fix it.

**Comment by Schetkiglobe** [comment] 2023-12-20 19:15
> salve, the new version of the plugin (3 and up) is a complete reimplementation on the Android side that uses Health Connect instead of Google Fit. The issue you are reporting is that @awesome-cordova-plugins is not updated.
> 
> Solutions: use the latest v2, but stick to Google Fit, or do not use @awesome-cordova-plugins (<- I would recommend). It all depends on what API you want to use in the end.
> 
> Let me know if you manage to fix it.

I followed your advice. I uninstalled the @awesome-cordova-plugin and used the plugin in the following form: `cordova.plugins.requestAuthorization(datatypes, successCallback, errorCallback). `
Thanks for the support.
